DELIMITER //

USE `ADMIN`//

DROP PROCEDURE IF EXISTS `proc_IN`//

CREATE DEFINER=`root`@`localhost` PROCEDURE `proc_IN`(IN DNIS VARCHAR(20),
IN MSISDN VARCHAR(20),
IN AVPAIR1 VARCHAR(20),
IN AVPAIR2 VARCHAR(20),
IN GROUPID VARCHAR(20),
OUT DNS1 VARCHAR(15),
OUT DNS2 VARCHAR(15),
OUT AUTHSTAT VARCHAR(100))
    COMMENT 'Version 0.4.2 2/20/2015 for testing Author Jason Mallory Irridum Communications 2015'
BEGIN
declare dns1_tmp varchar(15);
declare dns2_tmp varchar(15);
DECLARE avpair1_tmp varchar(15);
DECLARE avpair2_tmp varchar(15);
DECLARE grpid_tmp varchar(15);
set dns1_tmp = '12.127.17.72';
SET dns2_tmp = '204.97.212.10';

BEGIN
DECLARE C_USER CURSOR FOR SELECT AVPAIR1, AVPAIR2, DNS1, DNS2, GROUPID FROM GRP, ALLMEMBER WHERE ALLMEMBER.GROUPID=GRP.GROUPID AND ALLMEMBER.MSISDN='newmsisdn' AND GRP.DNIS='newdnis'
	UNION
    SELECT AVPAIR1, AVPAIR2, DNS1, DNS2, GROUPID FROM GRP; 
OPEN C_USER;
FETCH C_USER INTO AVPAIR1, AVPAIR2, DNS1, DNS2, GROUPID;
LOOP
	FETCH C_USER INTO avpair1_tmp, avpair2_tmp, dns1_tmp, dns2_tmp, grpid_tmp;
    INSERT INTO duplog VALUES(DNIS, MSISDN, avpair1_tmp, avpair2_tmp, dns1_tmp,dns2_tmp, grpid_tmp, SYSDATE);
END LOOP;
IF C_USER%ROWCOUNT > 1 THEN
		INSERT INTO duplog VALUES(DNIS, MSISDN, AVPAIR1, AVPAIR2, DNS1,DNS2, GROUPID, SYSDATE);
			SET AUTHSTAT := 'ok';
		elseif C_USER%ROWCOUNT = 1 THEN
			SET AUTHSTAT := 'ok';
ELSE
			SET AUTHSTAT := NULL;
END IF;
            
CLOSE C_USER;
COMMIT;
END; 
END